#pragma once

#define GAME_NAME "Wallhala"
#define GAME_VERSION "0.1"

#define UPDATES_PER_SECOND 100.0f
#define SECONDS_PER_UPDATE (1.0f/UPDATES_PER_SECOND)

#define VIEWPORT_RATIO  (16.0f/9.0f)
#define VIEWPORT_LEFT   -100.0f
#define VIEWPORT_RIGHT   100.0f
#define VIEWPORT_BOTTOM (VIEWPORT_LEFT /VIEWPORT_RATIO)
#define VIEWPORT_TOP    (VIEWPORT_RIGHT/VIEWPORT_RATIO)
#define VIEWPORT_HEIGHT (VIEWPORT_TOP - VIEWPORT_BOTTOM)

#define GAMEFIELD_LEFT   (VIEWPORT_LEFT)
#define GAMEFIELD_RIGHT  (VIEWPORT_RIGHT)
#define GAMEFIELD_BOTTOM (VIEWPORT_LEFT/2)
#define GAMEFIELD_TOP    (VIEWPORT_RIGHT/2)
#define GAMEFIELD_HEIGHT (GAMEFIELD_TOP - GAMEFIELD_BOTTOM)
#define GAMEFIELD_CENTER_CORRECTION ((VIEWPORT_TOP-GAMEFIELD_TOP)*(-1))

#define TILE_SIZE (VIEWPORT_RIGHT/10.0f)
#define PIXELS_PER_TILE 64.0f
#define PIXELS_PER_UNIT (PIXELS_PER_TILE/TILE_SIZE)

#define FONT_SIZE 32
